general {
	lock_cmd = hyprlock
	before_sleep_cmd = playerctl pause
	ignore_dbus_inhibit = false
}
listener {
	timeout = 170
	on-timeout = notify-send -t 5000 "Session manager" "Locking session in 10 seconds"
}
listener {
	timeout = 180
	on-timeout = hyprlock
}
