background {
    path = screenshot
    blur_size = 6
    blur_passes = 4
    brightness = 0.3
}
input-field {
    size = 200, 30
    outline_thickness = 1
    rounding = 10
    outer_color = rgb(110, 110, 110)
    inner_color = rgb(38, 38, 38)
    font_color = rgb(225, 225, 225)
    check_color = rgb(200, 200, 200)
    fail_color = rgb(152, 152, 152)
    placeholder_text = 
    fade_on_empty = false
    halign = center
    valign = center
}
label {
    text = cmd[update:1000] date +"%I:%M:%S %p"
    color = rgba(225, 225, 225, 0.8)
    font_size = 60
    font_family = Noto Sans
    position = 0, 120
    halign = center
    valign = center
}
label {
    text = $LAYOUT
    color = rgba(225, 225, 225, 0.8)
    font_size = 15
    font_family = Noto Sans
    position = 0, 35
    halign = center
    valign = center
}
label {
    text = cmd[update:1000] player=$(playerctl -l 2>/dev/null | head -n 1); [ -n "$player" ] && playerctl -p "$player" metadata --format "{{title}} - {{artist}}" || echo "No music playing"
    color = rgba(225, 225, 225, 0.8)
    font_size = 15
    font_family = Noto Sans
    position = 0, -350
    halign = center
    valign = center
}
label {
    text = cmd[update:1000] uptime -p
    color = rgba(225, 225, 225, 0.8)
    font_size = 11
    font_family = Noto Sans
    position = 0, -400
    halign = center
    valign = center
}
