require("startup").setup({
	header = {
		type = "text",
		oldfiles_directory = false,
		align = "center",
		fold_section = false,
		title = "Header",
		margin = 5,
		content = {
			[[										  ]],
			[[    _   __           _    ______        ]],
			[[   / | / /__  ____  | |  / /  _/___ ___ ]],
			[[  /  |/ / _ \/ __ \ | | / // // __ `__ \]],
			[[ / /|  /  __/ /_/ / | |/ // // / / / / /]],
			[[/_/ |_/\___/\____/  |___/___/_/ /_/ /_/ ]],
			[[                                        ]],
		},
		highlight = "Statement",
		default_color = "",
		oldfiles_amount = 0,
	},
	-- name which will be displayed and command
	body = {
		type = "mapping",
		oldfiles_directory = false,
		align = "center",
		fold_section = false,
		title = "Basic Commands",
		margin = 5,
		content = {
			{ " New File", "lua require'startup'.new_file()", "<leader>nf" },
			{ " Find File", "Telescope find_files", "<leader>ff" },
			{ " Find Word", "Telescope live_grep", "<leader>fg" },
			{ " Recent Files", "Telescope oldfiles", "<leader>rf" },
			{ " File Browser", "NvimTreeToggle", "<c-e>" },
		},
		highlight = "String",
		default_color = "",
		oldfiles_amount = 0,
	},
	body_2 = {
		type = "oldfiles",
		oldfiles_directory = true,
		align = "center",
		fold_section = false,
		title = "",
		margin = 5,
		content = "",
		highlight = "String",
		oldfiles_amount = 10,
	},
	options = {
		after = function()
			require("startup.utils").oldfiles_mappings()
		end,
		mapping_keys = true,
		cursor_column = 0.5,
		empty_lines_between_mappings = true,
		disable_statuslines = true,
		paddings = { 3, 3, 3 },
	},
	mappings = {
		execute_command = "<CR>",
		open_file = "o",
		open_file_split = "<c-o>",
		open_section = "<TAB>",
		open_help = "?",
	},
	parts = { "header", "body", "body_2" },
})
