## name: Rosé Pine
## author: mvllow
## license: MIT
## upstream: https://github.com/rose-pine/kitty/blob/main/dist/rose-pine.conf
## blurb: All natural pine, faux fur and a bit of soho vibes for the classy minimalist

foreground               #f4f4f4
background               #070707
selection_foreground     #f4f4f4
selection_background     #515151

cursor                   #666666
cursor_text_color        #f4f4f4

url_color                #e8e8e8

active_tab_foreground    #f4f4f4
active_tab_background    #3a3a3a
inactive_tab_foreground  #878787
inactive_tab_background  #232323

active_border_color      #8e8e8e
inactive_border_color    #515151

# black
color0   #3a3a3a
color8   #878787

# red
color1   #eaeaea
color9   #eaeaea

# green
color2   #8e8e8e
color10  #8e8e8e

# yellow
color3   #f4f4f4
color11  #f4f4f4

# blue
color4   #d8d8d8
color12  #d8d8d8

# magenta
color5   #e8e8e8
color13  #e8e8e8

# cyan
color6   #eaeaea
color14  #eaeaea

# white
color7   #f4f4f4
color15  #f4f4f4

